"""Presentation helpers for the web CRM layer."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, datetime
from zoneinfo import ZoneInfo

_CRM_TZ = ZoneInfo("America/Santiago")
_FOLLOW_UP_HEADER = re.compile(r"^\[(\d{2}/\d{2}/\d{4} \d{2}:\d{2})\]\s+(.+)$")


@dataclass(frozen=True, slots=True)
class FollowUpNote:
    timestamp: str
    author: str
    text: str


@dataclass(frozen=True, slots=True)
class ParsedLeadComments:
    original_request: str
    notes: list[FollowUpNote]
    is_fallback: bool = False


def parse_lead_comments(raw_comments: str | None) -> ParsedLeadComments:
    """Split the raw comentarios blob into original request and follow-up notes.

    The parser only recognizes the exact format generated by the current
    server-side append flow. If any block is malformed, it fails closed and
    returns the full content as the original request with no extracted notes.
    """

    raw = (raw_comments or "").strip()
    if not raw:
        return ParsedLeadComments(original_request="", notes=[])

    blocks = raw.split("\n\n")
    if len(blocks) == 1:
        return ParsedLeadComments(original_request=raw, notes=[])

    original_request = blocks[0].strip()
    notes: list[FollowUpNote] = []

    for block in blocks[1:]:
        parsed = _parse_follow_up_block(block)
        if parsed is None:
            return ParsedLeadComments(original_request=raw, notes=[], is_fallback=True)
        notes.append(parsed)

    return ParsedLeadComments(original_request=original_request, notes=notes)


def _parse_follow_up_block(block: str) -> FollowUpNote | None:
    lines = block.splitlines()
    if not lines:
        return None

    header = lines[0].strip()
    match = _FOLLOW_UP_HEADER.match(header)
    if match is None:
        return None

    body = "\n".join(lines[1:]).strip()
    return FollowUpNote(timestamp=match.group(1), author=match.group(2).strip(), text=body)


def build_timeline_items(
    events: list[dict],
    notes: list[FollowUpNote],
    state_changes: list[dict] | None = None,
) -> list[dict]:
    """Merge assignment events, state-change events and human notes into one timeline.

    Assignment events (migration 007) and state-change events (migration 008) carry
    full-precision ``fecha_hora`` (TIMESTAMPTZ); human notes carry minute-precision
    ``dd/mm/YYYY HH:MM`` strings generated in America/Santiago. All are normalized to
    aware datetimes in America/Santiago for a stable descending sort.

    The sort is deterministic: primary key is the timestamp (descending) and, on an
    exact tie, a fixed source rank keeps assignment events before state-change events
    before notes (``event`` < ``state_change`` < ``note``). Python's stable sort then
    preserves the repository's own deterministic ordering (``fecha_hora DESC,
    id_auditoria DESC``) for ties within a single source.
    """
    items: list[dict] = []

    for event in events:
        timestamp = _to_santiago(event.get("fecha_hora"))
        if timestamp is None:
            continue
        items.append(
            {
                "kind": "event",
                "timestamp": timestamp,
                "display_time": timestamp.strftime("%d/%m/%Y %H:%M"),
                "actor": event.get("actor_subject"),
                "asesor_nombre": event.get("asesor_nombre"),
                "estado_anterior": event.get("estado_anterior"),
                "estado_nuevo": event.get("estado_nuevo"),
            }
        )

    for change in state_changes or []:
        timestamp = _to_santiago(change.get("fecha_hora"))
        if timestamp is None:
            continue
        items.append(
            {
                "kind": "state_change",
                "timestamp": timestamp,
                "display_time": timestamp.strftime("%d/%m/%Y %H:%M"),
                "actor": change.get("actor_subject"),
                "estado_anterior": change.get("estado_anterior"),
                "estado_nuevo": change.get("estado_nuevo"),
            }
        )

    for note in notes:
        items.append(
            {
                "kind": "note",
                "timestamp": _parse_note_timestamp(note.timestamp),
                "display_time": note.timestamp,
                "author": note.author,
                "text": note.text,
            }
        )

    items.sort(key=_timeline_sort_key, reverse=True)
    return items


_SOURCE_RANK: dict[str, int] = {"event": 0, "state_change": 1, "note": 2}


def _timeline_sort_key(item: dict) -> tuple[datetime, int]:
    """Stable, deterministic sort key: timestamp desc, then fixed source rank asc."""
    return (item["timestamp"], -_SOURCE_RANK[item["kind"]])


def _to_santiago(value: object) -> datetime | None:
    """Normalize a database timestamp to an aware America/Santiago datetime."""
    if value is None or not isinstance(value, datetime):
        return None
    if value.tzinfo is None:
        return value.replace(tzinfo=_CRM_TZ)
    return value.astimezone(_CRM_TZ)


def _parse_note_timestamp(value: str) -> datetime:
    """Parse a follow-up note timestamp written by the server in America/Santiago."""
    try:
        return datetime.strptime(value, "%d/%m/%Y %H:%M").replace(tzinfo=_CRM_TZ)
    except ValueError:
        return datetime.min.replace(tzinfo=_CRM_TZ)


def state_history_cutover_notice(cutover: date | None) -> str:
    """Build the honest coverage notice for general state-change history.

    The cutover date is never invented during development: it comes from a
    reproducible configuration source (``LEAD_STATE_HISTORY_CUTOVER``). When it is
    not configured, the notice states the coverage boundary without a fake date.
    """
    if cutover is None:
        return (
            "El historial de cambios generales de estado se muestra desde la "
            "puesta en produccion de la migracion 008. Las asignaciones "
            "anteriores se conservan."
        )
    return (
        f"El historial de cambios generales de estado se muestra desde el "
        f"{cutover.strftime('%d/%m/%Y')} (corte de la migracion 008). Las "
        "asignaciones anteriores se conservan."
    )
