"""Presentation helpers for the web CRM layer."""

from __future__ import annotations

import re
from dataclasses import dataclass

_FOLLOW_UP_HEADER = re.compile(r"^\[(\d{2}/\d{2}/\d{4} \d{2}:\d{2})\]\s+(.+)$")


@dataclass(frozen=True, slots=True)
class FollowUpNote:
    timestamp: str
    author: str
    text: str


@dataclass(frozen=True, slots=True)
class ParsedLeadComments:
    original_request: str
    notes: list[FollowUpNote]
    is_fallback: bool = False


def parse_lead_comments(raw_comments: str | None) -> ParsedLeadComments:
    """Split the raw comentarios blob into original request and follow-up notes.

    The parser only recognizes the exact format generated by the current
    server-side append flow. If any block is malformed, it fails closed and
    returns the full content as the original request with no extracted notes.
    """

    raw = (raw_comments or "").strip()
    if not raw:
        return ParsedLeadComments(original_request="", notes=[])

    blocks = raw.split("\n\n")
    if len(blocks) == 1:
        return ParsedLeadComments(original_request=raw, notes=[])

    original_request = blocks[0].strip()
    notes: list[FollowUpNote] = []

    for block in blocks[1:]:
        parsed = _parse_follow_up_block(block)
        if parsed is None:
            return ParsedLeadComments(original_request=raw, notes=[], is_fallback=True)
        notes.append(parsed)

    return ParsedLeadComments(original_request=original_request, notes=notes)


def _parse_follow_up_block(block: str) -> FollowUpNote | None:
    lines = block.splitlines()
    if not lines:
        return None

    header = lines[0].strip()
    match = _FOLLOW_UP_HEADER.match(header)
    if match is None:
        return None

    body = "\n".join(lines[1:]).strip()
    return FollowUpNote(timestamp=match.group(1), author=match.group(2).strip(), text=body)
